//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLaptopHooli.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietdonhang
    {
        public int id { get; set; }
        public int idDonHang { get; set; }
        public int idSanPham { get; set; }
        public int SoLuong { get; set; }
        public int GiaTien { get; set; }
    
        public virtual donhang donhang { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
